### ISSUE TITLE
Bug in the link from Language filter

### ISSUE THREAD

**Issue by yukakou** [NetAppDocs/netapp-solutions#74] opened 2021-05-12 07:29 UTC
Page: [TR-4841: Hybrid Cloud AI Operating System with Data Caching](https://docs.netapp.com/us-en/netapp-solutions/ai/hcaios_executive_summary.html)

I cannot see Japanese translation of this TR by selecting Japanese from the Language filter. Can you please fix it?

Thanks,
Yuka

**Comment by akseldavis** [comment] 2021-05-15 04:13
Duplicate of #69

**Closed by akseldavis** 2021-05-15 04:13 UTC
