### ISSUE TITLE
NFS.MaxQueueDepth

### ISSUE THREAD

**Issue by Myer** [NetAppDocs/netapp-solutions#185] opened 2022-02-24 16:40 UTC
Page: [Recommended ESXi host and other ONTAP settings](https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_recommended_esxi_host_and_other_ontap_settings.html)

As mentioned here [https://kb.vmware.com/s/article/86331?lang=en_US](https://kb.vmware.com/s/article/86331?lang=en_US) setting the NFS.MaxQueueDepth advanced configuration does not work with ESXi 7.0U1-U2. (I guess it also does not really work if you set it through ONTAP Tools.)
You need to manually configure this setting for each datastore (on each ESXi). Apparently this is fixed with ESXi 7.0U3.

**Comment by kevin-hoke** [comment] 2022-08-02 16:11
@ChrisReno - can you comment on this issue so we can close it?

**Comment by ChrisReno** [comment] 2022-08-05 19:03
I looked into this. This setting is referenced here: 

https://docs.netapp.com/us-en/vsc-vasa-provider-sra-97/deploy/reference-esx-host-values-set-by-vsc-for-vmware-vsphere.html#esxi-advanced-configuration
https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_recommended_esxi_host_and_other_ontap_settings.html

For each link, when talking about **NFS.MaxQueueDepth** in the chart, we should include an * which indicates there is more information. 

Then after the table, where you are referencing the * include this text:

"NFS advanced configuration option MaxQueueDepth may not work as intended when using VMware vSphere ESXi 7.0.1 and VMware vSphere ESXi 7.0.2. Please reference this VMware KB for more information:
https://kb.vmware.com/s/article/86331?lang=en_US "

**Comment by kevin-hoke** [comment] 2022-08-23 14:03
@Myer, Content has been added to the documentation to address this issue.  If it answers your initial concerns, please close this issue and let me know if there are other concerns.  Thank you!

**Closed** 2022-08-23 14:19 UTC
