### ISSUE TITLE
Bug in the link from Language filter

### ISSUE THREAD

**Issue by yukakou** [NetAppDocs/netapp-solutions#70] opened 2021-05-12 07:27 UTC
Page: [NVA-1141: NetApp HCI with Anthos, design and deployment](https://docs.netapp.com/us-en/netapp-solutions/containers/anthos_concept_overview.html)

I cannot see Japanese translation of this TR by selecting Japanese from the Language filter. Can you please fix it?

Thanks,
Yuka

**Comment by akseldavis** [comment] 2021-05-15 04:12
Duplicate of #69

**Closed by akseldavis** 2021-05-15 04:12 UTC
