### ISSUE TITLE
Language Filter not working properly

### ISSUE THREAD

**Issue by yukakou** [NetAppDocs/netapp-solutions#56] opened 2021-04-16 10:08 UTC
Page: [TR-4861: Hybrid Cloud VDI with Virtual Desktop Service](https://docs.netapp.com/us-en/netapp-solutions/vdi-vds/hcvdivds_hybrid_cloud_vdi_with_virtual_desktop_service.html)

When I select Japanese from the language selector on TR-4861 page, it goes to the top page of NetApp Solutions.

**Comment by akseldavis** [comment] 2021-05-15 04:11
Duplicate of #69

**Closed by akseldavis** 2021-05-15 04:11 UTC
