### ISSUE TITLE
Bug in the link from Language filter

### ISSUE THREAD

**Issue by yukakou** [NetAppDocs/netapp-solutions#71] opened 2021-05-12 07:27 UTC
Page: [TR-4857: NetApp HCI with Cisco ACI](https://docs.netapp.com/us-en/netapp-solutions/infra/hcicaci_netapp_hci_with_cisco_aci.html)

I cannot see Japanese translation of this TR by selecting Japanese from the Language filter. Can you please fix it?

Thanks,
Yuka

**Comment by akseldavis** [comment] 2021-05-15 04:12
Duplicate of #69

**Closed by akseldavis** 2021-05-15 04:12 UTC
