### ISSUE TITLE
Bug in the link from Language filter

### ISSUE THREAD

**Issue by yukakou** [NetAppDocs/netapp-solutions#73] opened 2021-05-12 07:29 UTC
Page: [TR-4834: NetApp and Iguazio for MLRun Pipeline](https://docs.netapp.com/us-en/netapp-solutions/ai/mlrun_introduction.html)

I cannot see Japanese translation of this TR by selecting Japanese from the Language filter. Can you please fix it?

Thanks,
Yuka

**Comment by akseldavis** [comment] 2021-05-15 04:13
Duplicate of #69

**Closed by akseldavis** 2021-05-15 04:13 UTC
