### ISSUE TITLE
Bug in the link from Language filter

### ISSUE THREAD

**Issue by yukakou** [NetAppDocs/netapp-solutions#72] opened 2021-05-12 07:28 UTC
Page: [TR-4861: Hybrid Cloud VDI with Virtual Desktop Service](https://docs.netapp.com/us-en/netapp-solutions/vdi-vds/hcvdivds_hybrid_cloud_vdi_with_virtual_desktop_service.html)

I cannot see Japanese translation of this TR by selecting Japanese from the Language filter. Can you please fix it?

Thanks,
Yuka

**Comment by akseldavis** [comment] 2021-05-15 04:13
Duplicate of #69

**Closed by akseldavis** 2021-05-15 04:13 UTC
